# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d08d1f5dc0e150e2c23c5993d16add5a9b89a9fa5983bd4cd2af2f3e880a1f273473d3d43faab53b197df882ab8be74f99444c52c8438b5c67eb265e5ba96ea

test:
  secret_key_base: fcdd41de4def203f32f466a3864c37b151dfbe171d79e1eb6814e77691c31a5e7ff4c6bb97baa6902289919b509b45e1827fa18ac78fe17f6ad64e9b97ef7f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
